---
env:
    browser: true
    es6: true
extends:
    - eslint:recommended
    - prettier
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 6
rules:
    indent:
        - error
        - 4
        - SwitchCase: 1
          ignoredNodes:
              - TemplateLiteral
    linebreak-style:
        - error
        - unix
    multiline-ternary:
        - error
        - always-multiline
    no-console: warn
    no-template-curly-in-string: warn
    no-useless-concat: error
    prefer-template: error
    quotes:
        - error
        - double
    semi:
        - error
        - always
