---
default: true
MD003:
    style: atx # hastags for headings
MD007: # nested unordered lists
    indent: 4
MD013: false # don't limit line length
MD026: false # allow punctuation in headings
MD029:
    style: one # ordered list items should all be 1.
MD030: # spaces after list marker
    ol_single: 3
    ul_single: 3
    ol_multi: 3
    ul_multi: 3
MD035:
    style: --- # hr
MD046:
    style: fenced # code blocks
MD048:
    style: backtick # code fence
