---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=150"]
          - id: check-byte-order-marker
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
            args: ["--allow-multiple-documents"]
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: pretty-format-json
            args: ["--autofix", "--indent", "4"]
          - id: trailing-whitespace
