---
extends:
    - stylelint-config-standard
    - stylelint-config-prettier
plugins:
    - "@rp-magrathea/stylelint-alphabetical-clockwise-order"
    - stylelint-no-unsupported-browser-features
    - stylelint-order
rules:
    at-rule-no-unknown:
        - true
        - ignoreAtRules:
              - extend
    at-rule-no-vendor-prefix: true
    comment-empty-line-before:
        - always
        - except:
              - first-nested
          ignore:
              - after-comment
    custom-property-empty-line-before: null
    declaration-block-single-line-max-declarations: 2
    font-family-name-quotes: always-unless-keyword
    function-url-quotes: always
    media-feature-name-no-vendor-prefix: true
    no-descending-specificity: true
    no-duplicate-selectors:
        - true
        - severity: warning
    order/order:
        - type: at-rule
          name: extend
        - custom-properties
        - dollar-variables
        - at-variables
        - declarations
        - rules
        - at-rules
        - less-mixins
    plugin/no-unsupported-browser-features:
        - true
        - severity: warning
    plugin/properties-alphabetical-clockwise-order:
        - true
        - severity: error
    property-no-vendor-prefix: true
    selector-attribute-quotes: always
    selector-no-vendor-prefix: true
    value-no-vendor-prefix: true
