---
name: Linter

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          CSS_FILE_NAME: .stylelintrc.yml
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH:
          VALIDATE_ALL_CODEBASE: true
